src/ask/ask/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include, handler404, handler500
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('qa.urls', namespace='qa')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'qa.views.error404'
handler500 = 'qa.views.error500'

src/ask/qa/urls.py
# encoding=utf-8
from django.conf.urls import url

from . import url_ajax
from . import views

urlpatterns = [

    url(r'^$', views.question_list, name='question-list'),

    url(r'signup/$', views.singup, name='singup'),
    url(r'settings/$', views.user_settings, name='user-settings'),
    url(r'login/$', views.user_login, name='login'),
    url(r'logout/$', views.user_logout, name='logout'),

    url(r'question/(?P<id>\d+)/$', views.question_detail, name='question-detail'),
    url(r'answer/(?P<id>\d+)/$', views.answer, name='answer'),
    url(r'ask/$', views.ask_question, name='ask-question'),
    url(r'question/edit/(?P<id>\d+)/$', views.question_edit, name='question-edit'),
    url(r'popular/$', views.popular_list, name='popular-question-list'),
    url(r'new/$', views.question_list, name='new-question-list'),
    url(r'my_question/$', views.user_question, name='user-question-list'),
    url(r'tag/(?P<id>\d+)/$', views.question_by_tag, name='questions-by-tag'),
    url(r'tags/$', views.tags, name='tags'),
    url(r'search/$', views.search, name='search'),

    url(r'about/$', views.about, name='about'),
    url(r'blog/$', views.in_dev, name='in-development')

    ] + url_ajax.urlpatterns

src/ask/qa/models.py
# encoding=utf-8

from os import path
from os import remove, rmdir

from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.db.models import Count, Q
from django.db.models.signals import post_save, pre_save, pre_delete


class TagManager(models.Manager):

    def tags(self):
        return self.all().filter(question__published=True).annotate(count=Count('question'))


class Tag(models.Model):
    objects = TagManager()
    MAX_TAG_COUNT = 5
    name = models.CharField(max_length=15, unique=True, blank=False)

    def __str__(self):
        return self.name


class QuestionManager(models.Manager):

    def user_or_published(self, user):
        if user.is_authenticated:
            return self.all().filter(Q(published=True) | Q(author=user))
        else:
            return self.all().filter(published=True)

    def new(self, user):
        return self.user_or_published(user).order_by('-added_at')

    def popular(self, user):
        return self.user_or_published(user).order_by('-rating')

    def by_tag(self, tag, user):
        return self.user_or_published(user).filter(tags=tag)

    def user_question(self, user):
        return self.all().filter(author=user)


class Question(models.Model):
    objects = QuestionManager()
    title = models.CharField(max_length=150)
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='author', blank=True, null=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='user_question_likes', blank=True)
    tags = models.ManyToManyField(Tag)
    published = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'
        ordering = ['-added_at']

    def __str__(self):
        return self.title


# Answer - ответ
class Answer(models.Model):

    text = models.TextField()                               # text - текст ответа
    added_at = models.DateTimeField(auto_now_add=True)      # added_at - дата добавления ответа
    question = models.ForeignKey(Question, related_name='answers', on_delete=models.CASCADE)  # question - вопрос, к которому относится ответ
    author = models.ForeignKey(settings.AUTH_USER_MODEL)                        # author - автор ответа
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='user_answer_likes', blank=True)
    rating = models.IntegerField(default=0)
    correct = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'
        ordering = ['-added_at']

    def __str__(self):
        return self.text


def get_image_path(instance, filename):
    return path.join('avatars', str(instance.id), filename)


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=15, blank=True)
    image = models.ImageField(upload_to=get_image_path, blank=True)
    score = models.IntegerField(default=0)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()

    def save(self, *args, **kwargs):
        if not self.name:
            index = self.user.username.find('@')
            if index != -1:
                self.name = self.user.username[:index]
            else:
                self.name = self.user.username
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


@receiver(pre_save, sender=UserProfile)
def auto_delete_image_on_change(sender, instance, **kwargs):
    if instance.pk:
        try:
            old_image = UserProfile.objects.get(pk=instance.pk).image
        except UserProfile.DoesNotExist:
            return False
        if old_image:
            if old_image != instance.image:
                if path.isfile(old_image.path):
                    remove(old_image.path)


@receiver(pre_delete, sender=UserProfile)
def auto_delete_image_on_delete(sender, instance, **kwargs):
    if instance.image:
        if path.isfile(instance.image.path):
            image_dir = path.dirname(instance.image.path)
            remove(instance.image.path)
            rmdir(image_dir)

src/ask/qa/views.py
# encoding=utf-8

import json

from django import forms
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, reverse, redirect, Http404
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.validators import validate_email

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST

from .models import Question, Answer, Tag
from .forms import AnswerForm, NewUserForm, LoginUserForm, UserForm, UserProfileForm, AskModelForm

OBJECT_PER_PAGE = 10


class AjaxHttpResponse(HttpResponse):
    def __init__(self, status='ok', **kwargs):
        kwargs['status'] = status
        super(AjaxHttpResponse, self).__init__(
            content=json.dumps(kwargs),
            content_type='application/json; charset=utf-8', )


class ErrorAjaxHttpResponse(AjaxHttpResponse):
    def __init__(self, code, message):
        super(ErrorAjaxHttpResponse, self).__init__(status='error',
                                                    code=code, message=message)


def test(request, *args, **kwargs):
    return HttpResponse('OK')


def ajax_test(request, *args, **kwargs):
    return AjaxHttpResponse()


def paginate(request, object_list):
    paginator = Paginator(object_list, OBJECT_PER_PAGE)

    try:
        objects = paginator.page(request.GET.get('page'))
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)

    return objects


def login_required_ajax(view):
    def view2(request, *args, **kwargs):
        if request.user.is_authenticated():
            return view(request, *args, **kwargs)
        elif request.is_ajax():
            return ErrorAjaxHttpResponse(
                code='no_auth',
                message='Not authenticated'
            )
        else:
            redirect('qa:login')

    return view2


@require_GET
def question_list(request, *args, **kwargs):
    q_list = Question.objects.new(request.user)
    questions = paginate(request, q_list)
    context = {'questions': questions,
               'title': 'New Questions',
               'other_link':
                   [
                       {'title': 'Hot Question',
                        'url': reverse('qa:popular-question-list')},
                       {'title': 'My Question',
                        'url': reverse('qa:user-question-list')}
                   ]
               }

    return render(request, 'qa/questions.html', context)


@require_GET
def popular_list(request, *args, **kwargs):
    q_list = Question.objects.popular(request.user)
    questions = paginate(request, q_list)
    context = {'questions': questions,
               'title': 'Hot Question',
               'other_link':
                   [
                       {'title': 'New Question',
                        'url': reverse('qa:new-question-list')},
                       {'title': 'My Question',
                        'url': reverse('qa:user-question-list')}
                   ]
               }

    return render(request, 'qa/questions.html', context)


@require_GET
def question_by_tag(request, *arg, **kwargs):
    tag_id = kwargs.get('id')
    tag = get_object_or_404(Tag, id=tag_id)
    q_list = Question.objects.by_tag(tag, request.user)
    questions = paginate(request, q_list)
    context = {'questions': questions,
               'title': 'By tag: {}'.format(tag.name.upper()),
               }

    return render(request, 'qa/questions.html', context)


@require_GET
@login_required
def user_question(request, *arg, **kwargs):
    q_list = Question.objects.user_question(request.user)
    questions = paginate(request, q_list)
    context = {'questions': questions,
               'title': 'My question',
               'other_link':
                   [
                       {'title': 'New Question',
                        'url': reverse('qa:new-question-list')},
                       {'title': 'Hot Question',
                        'url': reverse('qa:popular-question-list')},
                   ]
               }

    return render(request, 'qa/questions.html', context)


@require_GET
def question_detail(request, *args, **kwargs):
    question_id = kwargs.get('id', None)
    question = get_object_or_404(Question, pk=question_id)
    answers = Answer.objects.filter(question=question).order_by('-rating')
    context = {'question': question,
               'answers': answers,
               'form': AnswerForm,
               'title': 'Question detail page'}
    return render(request, 'qa/question.html', context)


@login_required
@require_GET
def answer(request, *args, **kwargs):
    answer_id = kwargs.get('id', None)
    answer = get_object_or_404(Answer, pk=answer_id)
    json = request.GET.get('json')
    if json:
        return AjaxHttpResponse(id=answer.id, text=answer.text)
    context = {'answer': answer, 'question': answer.question}
    return render(request, 'qa/answer.html', context)


@login_required
def ask_question(request, *args, **kwargs):
    if request.method == "POST":
        form = AskModelForm(request.POST, initial={'author': request.user})
        if form.is_valid():
            question = form.save()
            messages.add_message(request, messages.SUCCESS, 'New question added.')
            return redirect(reverse('qa:question-detail', kwargs={'id': question.pk}))
    else:
        form = AskModelForm()
    context = {'form': form,
               'url': reverse('qa:ask-question'),
               'title': 'New question',
               'button': 'ASK'}
    return render(request, 'qa/ask.html', context)


@login_required
def question_edit(request, *args, **kwargs):
    question_id = kwargs.get('id', None)
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        raise Http404()

    if request.method == 'POST':
        form = AskModelForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Question saved.')
            return redirect(reverse('qa:question-detail', kwargs={'id': question_id}))
    else:
        form = AskModelForm(instance=question)

    context = {'form': form,
               'url': reverse('qa:question-edit', kwargs={'id': question_id}),
               'title': 'Edit question:',
               'button': 'SAVE',
               'question_id': question_id}
    return render(request, 'qa/ask.html', context)


@require_GET
def tags(request, *args, **kwargs):
    context = {'tags': Tag.objects.tags()}
    return render(request, 'core/tags.html', context)


##################################################
#                    LOGIN                       #
##################################################


def singup(request, *args, **kwargs):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, user=new_user)
            return redirect('qa:question-list')
    else:
        form = NewUserForm()

    context = {'forms': [form], 'title': 'Registration:'}
    return render(request, 'auth/singup.html', context)


@require_GET
def user_logout(request, *args, **kwargs):
    logout(request)
    return redirect('qa:question-list')


def user_login(request, *args, **kwargs):
    if request.method == 'POST':
        next_param = request.GET.get('next')
        form = LoginUserForm(request.POST)
        if form.is_valid():
            if form.user is not None:
                login(request, form.user)
            return redirect(next_param or 'qa:question-list')
    else:
        form = LoginUserForm()

    context = {'forms': [form], 'title': 'Welcome'}
    return render(request, 'auth/login.html', context)


@login_required
@transaction.atomic
def user_settings(request, *args, **kwargs):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        user_profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and user_profile_form.is_valid():
            user_form.save()
            user_profile_form.save()
            messages.add_message(request, messages.SUCCESS, 'Your profile was successfully updated!')
            return redirect('qa:user-settings')
        else:
            pass
            # messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        user_profile_form = UserProfileForm(instance=request.user.userprofile)
    context = {
        'forms': [ user_form, user_profile_form ]
    }
    return render(request, 'auth/settings.html', context)


def about(request, *args, **kwargs):
    return render(request, 'core/about.html')


def in_dev(request, *args, **kwargs):
    return render(request, 'core/in_development.html')


##################################################
#                     AJAX                       #
##################################################

@require_POST
@login_required_ajax
def ajax_question_like(request, *args, **kwargs):
    q_id = kwargs.get('id')
    try:
        question = Question.objects.get(pk=q_id)
    except Question.DoesNotExist:
        return ErrorAjaxHttpResponse(code='not_found', message='Question not found.')

    if request.user not in question.likes.all():
        question.likes.add(request.user)
        question.rating = len(question.likes.all())
        question.save()
        return AjaxHttpResponse(id=question.id, rating=question.rating, message='New like to question added.')
    else:

src/ask/templates/qa/answer.html
{% spaceless %}
    <div id="answer-{{ answer.id }}">
        <div class="media answer-wrapper">
            <div class="media-left">

                <img class="media-object user-avatar"
                     src="{% if answer.author.userprofile.image %}
                        {{ answer.author.userprofile.image.url }}
                    {% else %}
                        {{ default_avatar }}
                    {% endif %}"
                     alt="...">
                <p class="text-center">{{ answer.author.userprofile }}</p>

                <div class="vote-like-wrapper">
                    <span id="a-like-{{ answer.id }}"
                          class="glyphicon a-like {% if user in answer.likes.all %}  i-like glyphicon-heart {% else %} glyphicon-triangle-top  {% endif %}"
                          href="{% url 'qa:ajax-answer-like' answer.id %}"></span>
                </div>
                <div class="vote-rating-wrapper">
                    <span id="a-rating-{{ answer.id }}">{{ answer.rating }}</span>
                </div>
                <div class="vote-like-wrapper">
                    <span class="glyphicon glyphicon-triangle-bottom a-dislike"
                          href="{% url 'qa:ajax-answer-dislike' answer.id %}"></span>
                </div>

            </div>

            <div class="media-body {% if not user == question.author and answer.correct %} a-correct-flag  {% endif %}">

                {% if user == answer.author %}
                    <div class="right answer-nav">
                        <div class="block-inline">
                            <button class="btn btn-default btn-sm a-edit" data-id="{{ answer.id }}" role="button"
                                    data-toggle="modal" data-target="#edit-answer_modal"
                                    data-action-url="{% url 'qa:answer' answer.id %}">Edit
                            </button>
                        </div>
                        <div class="block-inline">
                            <button class="btn btn-danger btn-sm a-delete" role="button"
                                    data-toggle="modal" data-target="#delete_answer_confirm_modal"
                                    data-id = "{{ answer.id }}">Delete</button>
                        </div>
                    </div>
                {% endif %}

                <div id="answer-text-{{ answer.id }}" class="answer-text">
                    {{ answer.text | safe }}
                </div>

                {% if user == question.author %}
                    <div class="checkbox" style="position: absolute; bottom: -10px; margin-left: 35%;margin-right: 40%">
                        <label>
                            <input class="a-correct" id="a-correct-{{ answer.id }}" type="checkbox"
                                    {% if answer.correct %}
                                   checked="checked" {% endif %}
                                   href="{% url 'qa:ajax-answer-correct' answer.id %}">
                            Correct!
                        </label>
                    </div>
                {% endif %}

            </div>
        </div>
        <hr class="detail-q-hr">
    </div>
{% endspaceless %}

src/ask/templates/qa/question.html
{% extends "core/base.html" %}
{% spaceless %}

    {% block title %}
        {% if user == question.author %}
            <div class="block-inline">
                <div class="q-edit-btn">
                    <a class="btn btn-default btn-sm" role="button" href="{% url 'qa:question-edit' question.id %}">Edit
                        question</a>
                </div>
            </div>
        {% endif %}
    {% endblock %}


    {% block content %}
        <div class="detail-q-wrapper">
            <div class="detail-q-content">

                <div class="right detail-q-user">
                    <p class="text-center">
                        <img class="user-avatar"
                             src="{% if question.author.userprofile.image %}
                            {{ question.author.userprofile.image.url }}
                        {% else %}
                            {{ default_avatar }}
                        {% endif %}" alt="...">
                    </p>
                    <p class="text-center">{{ question.author.userprofile }}</p>
                </div>

                <h1 class="detail-q-header">
                    {% if not question.published %}
                        <a class="unpublished" href="#">[Unpublished] {{ question.title }}</a>
                    {% else %}
                        <a href="#"> {{ question.title }}</a>
                    {% endif %}

                </h1>
                <p>{{ question.text | safe }}</p>
            </div>
            <div class="question-footer">

                <ul class="list-inline">
                    <li class="vote-like-wrapper">
                    <span id="q-like-{{ question.id }}"
                          class="glyphicon q-like detail-q-like {% if user in question.likes.all %} i-like glyphicon-heart {% else %} glyphicon-triangle-top  {% endif %}"
                          data-action-url="{% url 'qa:ajax-question-like' question.id %}"></span>
                    </li>
                    <li class="vote-rating-wrapper">
                        <span id="q-rating-{{ question.id }}">{{ question.rating }}</span>
                    </li>
                    <li class="vote-like-wrapper">
                    <span class="glyphicon glyphicon-triangle-bottom q-dislike"
                          data-action-url="{% url 'qa:ajax-question-dislike' question.id %}"></span>
                    </li>
                    <li>Tags:</li>
                    {% for tag in question.tags.all %}
                        <li><a href="{% url 'qa:questions-by-tag' tag.id %}">{{ tag }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <hr class="detail-q-hr">

        <!-- Modal -->
        <div class="modal fade" id="edit-answer_modal" role="dialog">
            <div class="modal-dialog modal-lg">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Edit answer for: {{ question.title }}</h4>
                    </div>
                    <div class="modal-body">
                        <input id="answer-edit-id" class="hidden">
                        <textarea id="answer-edit-textarea"></textarea>
                    </div>
                    <div class="modal-footer">
                        <button id="save-answer" class="btn btn-success" data-dismiss="modal"
                                data-action-url="{% url 'qa:ajax-edit-answer' %}">Save
                        </button>
                        <button id="close-answer" type="button" class="btn btn-default" data-dismiss="modal">Close
                        </button>
                    </div>
                </div>

            </div>
        </div>

        <div class="modal fade" id="delete_answer_confirm_modal" role="dialog">
            <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Delete answer:</h4>
                    </div>
                    <div class="modal-body">
                        <input id="answer-remove-id" class="hidden">
                        Are you sure?
                    </div>
                    <div class="modal-footer">
                        <button id="delete-answer-confirm" class="btn btn-danger" data-dismiss="modal"
                                data-action-url="{% url 'qa:ajax-remove-answer' %}">Delete
                        </button>
                        <button id="close-answer" type="button" class="btn btn-default" data-dismiss="modal">No
                        </button>
                    </div>
                </div>

            </div>
        </div>

        <div id="answers">

            {% for answer in answers %}
                {% include "qa/answer.html" with answer=answer question=question %}
            {% endfor %}

        </div>

        {% if user.is_authenticated %}

            <form class="form-horizontal" autocomplete="off" method="post">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
                    {% endfor %}
                {% endif %}

                {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label class="col-md-1 control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="col-md-11">
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <div class="col-md-1"></div>
                    <div class="col-md-11">
                        <input id="add-answer" class="btn btn-success" type="submit" value="Answer"
                               data-action-url="{% url 'qa:ajax-add-answer' question.id %}">
                    </div>
                </div>

            </form>
        {% else %}
            You must be authorized user for send answer.
            <a class="btn btn-success" role="button" href="{% url 'qa:login' %}">Login</a>
        {% endif %}
    {% endblock %}


    {% block script %}
        {% include "qa/script.html" %}
        <script>
            $(document).ready(addQuestionsAnswersEventHandler
            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        , showSuccessMsg("{{message}}")
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        , showWarningMsg("{{message}}")
                    {% endif %}
                {% endfor %}
            {% endif %}
            );
        </script>

    {% endblock %}
{% endspaceless %}

src/ask/templates/qa/questions.html
{% extends "core/base.html" %}

{% spaceless %}

    {% block title %}

        <div class="block-inline"><h3 class="current-content-title">{{ title }}</h3></div>
        {% for item in other_link %}
            <div class="block-inline"><h4 class="content-title"><a href={{ item.url }}> {{ item.title }}</a></h4></div>
        {% endfor %}

    {% endblock %}

    {% block content %}

        {% for question in questions %}
            <div class="media question">
                <div class="media-left">
                    <img class="media-object user-avatar"
                         src="{% if question.author.userprofile.image %}
                            {{ question.author.userprofile.image.url }}
                        {% else %}
                            {{ default_avatar }}
                        {% endif %}" alt="...">
                    <p class="text-center">{{ question.author.userprofile }}</p>
                </div>

                <div class="media-body">
                    <h3 class="media-heading"><a
                            href={% url 'qa:question-detail' question.id %}>
                        {% if not question.published %}
                            <span class="unpublished">[Unpublished]
                        {% else %}
                            <span>
                        {% endif %} {{ question.title }}  </span> </a>
                    </h3>
                    <p class="question-shot-text">{{ question.text|truncatewords_html:50|safe|striptags }}</p>

                    <div class="question-footer">
                        <ul class="list-inline">
                            <li>
                                <a href={% url 'qa:question-detail' question.id %}>Answers({{ question.answers.count }})</a>
                            </li>
                            {% if question.tags.all.count > 0 %}
                                <li>Tags:</li>
                            {% endif %}
                            {% for tag in question.tags.all %}
                                <li><a href="{% url 'qa:questions-by-tag' tag.id %}">{{ tag }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="media-right q-vote">
                <span id="q-like-{{ question.id }}"
                      class="glyphicon q-like {% if user in question.likes.all %} i-like glyphicon-heart {% else %} glyphicon-triangle-top {% endif %}"
                      data-action-url="{% url 'qa:ajax-question-like' question.id %}"></span>
                    <div class="vote-rating">
                        <span id="q-rating-{{ question.id }}">{{ question.rating }}</span>
                    </div>
                    <span class="glyphicon glyphicon-triangle-bottom q-dislike"
                          data-action-url="{% url 'qa:ajax-question-dislike' question.id %}" title='test'></span>
                </div>

            </div>

            <hr class="question-hr">
        {% endfor %}

    {% endblock %}


    {% block pagination %}
        {% if questions.paginator.num_pages > 1 %}
            <div id="pagination">
                <div class="row">
                    <div class="col-md-7 col-sm-9">
                        <nav aria-label="navigation">
                            <ul class="pager">
                                {% if questions.has_previous %}
                                    <li>
                                        <a href="?page={{ questions.previous_page_number }}">Previous</a>
                                    </li>
                                {% endif %}

                                <span class="current">
                                            page {{ questions.number }} of {{ questions.paginator.num_pages }}.
                                        </span>


                                {% if questions.has_next %}
                                    <li>
                                        <a href="?page={{ questions.next_page_number }}">Next</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endblock %}

    {% block script %}
        <script>
            $(document).ready(
                addQuestionsEventHandler()
            )
        </script>
    {% endblock %}

{% endspaceless %}