src/ask/ask/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include, handler404, handler500
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('qa.urls', namespace='qa')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'qa.views.error404'
handler500 = 'qa.views.error500'

src/ask/qa/urls.py
# encoding=utf-8
from django.conf.urls import url

from . import url_ajax
from . import views

urlpatterns = [

    url(r'^$', views.question_list, name='question-list'),

    url(r'signup/$', views.singup, name='singup'),
    url(r'settings/$', views.user_settings, name='user-settings'),
    url(r'login/$', views.user_login, name='login'),
    url(r'logout/$', views.user_logout, name='logout'),

    url(r'question/(?P<id>\d+)/$', views.question_detail, name='question-detail'),
    url(r'answer/(?P<id>\d+)/$', views.answer, name='answer'),
    url(r'ask/$', views.ask_question, name='ask-question'),
    url(r'question/edit/(?P<id>\d+)/$', views.question_edit, name='question-edit'),
    url(r'popular/$', views.popular_list, name='popular-question-list'),
    url(r'new/$', views.question_list, name='new-question-list'),
    url(r'my_question/$', views.user_question, name='user-question-list'),
    url(r'tag/(?P<id>\d+)/$', views.question_by_tag, name='questions-by-tag'),
    url(r'tags/$', views.tags, name='tags'),
    url(r'search/$', views.search, name='search'),

    url(r'about/$', views.about, name='about'),
    url(r'blog/$', views.in_dev, name='in-development')

    ] + url_ajax.urlpatterns

src/ask/templates/core/about.html
{% extends "core/base.html" %}
{% spaceless %}
    {% block title %}
        <div class="block-inline"><h3 class="current-content-title">About project</h3></div>
    {% endblock %}

    {% block content %}

        <p> Simple analog <a href="stackoverflow.com">Stackoverflow.com</a> project based on Django framework.</p>
        <h4>Used technologies:</h4>
        <ul>
            <li>Python</li>
            <li>Django</li>
            <li>HTML</li>
            <li>CSS</li>
            <li>Twitter Bootstrap</li>
            <li>JavaScript</li>
            <li>Jquery</li>
            <li>AJAX</li>
            <li>Git</li>
        </ul>
        <h4>For deployment use:</h4>
        <ul>
            <li>Ubuntu server</li>
            <li>Nginx</li>
            <li>Gunicorn</li>
            <li>PostgreSQL</li>
            <li>Supervisor</li>
        </ul>
        <h4>In future:</h4>
        <ul>
            <li>Elasticsearch</li>
            <li>Selery</li>
            <li>RabbitMQ</li>
        </ul>

    {% endblock %}

{% endspaceless %}

src/ask/templates/core/base.html
{% load static from staticfiles %}
{% spaceless %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Out of Memory Error</title>
        <link rel="stylesheet" type="text/css"
              href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/themes/prism.min.css">
        <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    </head>

    <body>

    <div id="git-form" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Github</h4>
                </div>
                <div class="modal-body">
                    <p class="text-center">
                        <small>We send github link on your mail.</small>
                    </p>
                    <p class="input-group">
                        <span class="input-group-addon"> <span class="glyphicon glyphicon-envelope"></span> </span>
                        <input id="git-email" class="form-control input-lg" name="email"
                               placeholder="example@example.com" type="text">
                    </p>
                </div>
                <div class="modal-footer">
                    <button id="git-send" type="submit" data-action-url="{% url 'qa:my-github' %}"
                            class="btn btn-success btn-default">Send me Git
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <header>

        {% block head %}
            <nav class="navbar navbar-fixed-top">
                <div class="container">
                    <div class="row">
                        <div class="col-md-11">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                        data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="{% url 'qa:question-list' %}"><span
                                        class="text-larger">{ ? } Out</span>of<span
                                        class="text-larger">MemoryError</span>
                                </a>
                            </div>
                            <div id="navbar" class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">
                                    <li>
                                        <a class="glyphicon glyphicon-search" href="{% url 'qa:search' %}"></a>
                                    </li>
                                    <li>
                                        <a href="{% url 'qa:in-development' %}">Blog</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'qa:about' %}">About</a>
                                    </li>
                                </ul>
                                <ul class="nav navbar-nav navbar-right nav-user">
                                    {% if user.is_authenticated %}
                                        <li class="hidden-xs"><img id="user-avatar" class="img-rounded"
                                                                   src="
                                                           {% if user.userprofile.image %}
                                                                    {{ user.userprofile.image.url }}
                                                           {% else %}
                                                               {{ default_avatar }}
                                                           {% endif %}
                                                            " alt="...X...">
                                        </li>
                                        <li><a href="{% url 'qa:user-settings' %}">{{ user.userprofile }}</a></li>
                                        <li><a href="{% url 'qa:logout' %}">Logout</a></li>
                                    {% else %}
                                        <li><a href="{% url 'qa:singup' %}">Sing up</a></li>
                                        <li><a href="{% url 'qa:login' %}"></span> Login</a></li>

                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <hr class="nav-hr">
            </nav>

        {% endblock %}

    </header>

    {% block container %}

        <div class="container main-content-container">
            <div class="row">
                <div class="col-md-11 questions">

                    <div class="col-md-9">
                        <div class="content-title-wrapper">

                            {% block title %}

                            {% endblock %}

                            <div class="ask-btm">
                                <h4 class="ask-btm-header">
                                    <a class="btn btn-default btn-sm" role="button" href="{% url 'qa:ask-question' %}">Ask
                                        Question </a>
                                </h4>
                            </div>

                        </div>

                        {% block content %}
                        {% endblock %}

                    </div>

                    <div class="col-md-3 hidden-xs hidden-sm">
                        <div class="tag-title-wrapper">
                            <h4 class="ask-btm-header">Popular tags</h4>
                        </div>

                        {% block sidebar %}

                            <div id="tagcloud">
                            </div>

                        {% endblock %}
                    </div>

                </div>
            </div>

            {% block pagination %}
            {% endblock %}

        </div>

    {% endblock %}

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-11">
                    <p>
{#                        <a type="button" data-toggle="modal" data-target="#git-form">Github</a>#}
                        © 2017 simple is better</p>
                </div>
            </div>
        </div>
    </footer>

    {% include "core/script.html" %}

    {% block script %}
    {% endblock %}

    </body>
    </html>

{% endspaceless %}

src/ask/templates/core/in_development.html
{% extends "core/base.html" %}
{% spaceless %}
    {% block content %}
        <div class="error-template">
            <h1>Ouch!</h1>
            <h2>This page in development</h2>
            <div class="error-details">
                I'm currently working on the development this functionality<br>
            </div>
            <div class="error-actions">
                <a class="text-larger" href="{% url 'qa:question-list' %}"></i> Take Me Home </a>
            </div>
        </div>
    {% endblock %}
{% endspaceless %}

src/ask/templates/core/script.html
{% load static from staticfiles %}
{% spaceless %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static "js/jquery.tagcloud.js" %}"></script>
    <script src="{% static "js/bootstrap-notify.min.js" %}"></script>

    <script src="{% static "js/main.js" %}"></script>
    <script>
        $(document).ajaxComplete(function () {
                $("#tagcloud a").tagcloud({
                    size: {start: 14, end: 36, unit: "px"},
                    color: {start: '#3498DB', end: '#46CFB0'}
                })
            },
            getTags('{% url 'qa:tags' %}')
        );
        $(document).ready(addBaseEventHandler)
    </script>
{% endspaceless %}

src/ask/templates/core/tags.html
{% for tag in tags %}
    <a href="{% url 'qa:questions-by-tag' tag.id %}" rel="{{ tag.count }}">{{ tag.name }}</a>
{% endfor %}